### PR TITLE
ml-kem: Update to FIPS 203

### LINKED ISSUE #46: ml-kem: update to FIPS 203 final
It's out: https://nvlpubs.nist.gov/nistpubs/fips/nist.fips.203.pdf

cc @bifurcation 

> ### C.2 Changes From FIPS 203 Initial Public Draft
>The differences between CRYSTALS-KYBER and ML-KEM as described in Appendix C were included
> in the initial public draft (ipd) of FIPS 203, which was posted on August 24, 2023. Based on
> comments submitted on the draft ML-KEM, domain separation was added to K-PKE.KeyGen to
> prevent the misuse of keys generated to target one security level from being used for a different
> security level when saving a key as a seed.
> Additionally, FIPS 203 ipd had inadvertently swapped the indices of matrix 𝐀̂in K-PKE.KeyGen and
> K-PKE.Encrypt. This was changed back in the final version of ML-KEM to match CRYSTALS-KYBER.

### PR DESCRIPTION
**Pull request by bifurcation**
Fixes #46 

This PR implements the two changes noted in Appendix C of [FIPS 203]:

* Domain separation in K-PKE.KeyGen
* Reversing the order of indices in array sampling

It turns out that we had already made the latter change in order to pass the existing test vectors.

Marking as WIP right now because I don't think updated test vectors have been published, and the current code fails on the current test vectors.  Should be a quick copy/paste update once the test vectors are available.

[FIPS 203]: https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.203.pdf

### CODE REVIEW

**Comment by tarcieri** [comment]
At some point the documentation (README.md, Cargo.toml) should also be updated to note it's no longer the draft construction

**Comment by tarcieri** [comment]
Looks like new test vectors are available here:

- https://github.com/usnistgov/ACVP-Server/tree/master/gen-val/json-files/ML-KEM-keyGen-FIPS203
- https://github.com/usnistgov/ACVP-Server/tree/master/gen-val/json-files/ML-KEM-encapDecap-FIPS203

**Comment by bifurcation** [comment]
@tarcieri - docs and test vectors updated, think this is ready for review

**Comment by bifurcation** [comment]
I went a little more radical on the test vector refactor than I might have, but honestly (a) the first effort was kinda half-assed, and (b) this way if NIST updates the vectors, we can just pull JSON files and not have to copy/paste a bunch of hex strings.

**Comment by newpavlov** [comment]
The JSON files are quite big (831 KB and 558 KB). I think we should either exclude them (and respective tests) from published crates (e.g. see the [`cmac`](https://github.com/RustCrypto/MACs/blob/master/cmac/Cargo.toml#L14) crate), or compress them better.

**Comment by bifurcation** [comment]
Good point @newpavlov, added those tests to the exclude list.

**Review by tarcieri — APPROVED** [review]

**Pull request merged**
