### PR TITLE
implement Decapsulate and Encapsulate from traits/kem

### PR DESCRIPTION
**Pull request by incertia**
updates ml-kem as advertised. this keeps EncapsulateDeterministic inside ml-kem though, perhaps this trait also deserves promotion to kem?

### CODE REVIEW

**Review by tarcieri — APPROVED** [review]
This seems like a good start.

Perhaps open an issue about `EncapsulateDeterministic` on the traits repo?

**Review by tarcieri — CHANGES_REQUESTED** [review]
Needs rustfmt and the trait isn't in scope everywhere it needs to be for the tests.

Also perhaps disable the minimal-versions check for now? Here's an example:

https://github.com/RustCrypto/traits/blob/25e5654bb0775d255abd937e3b3320b982f13da1/.github/workflows/elliptic-curve.yml#L62

**Comment by incertia** [comment]
Somehow adding the statement `use ::kem::{Decapsulate, Encapsulate}` still does not let the tests succeed

**Comment by tarcieri** [comment]
Looks like one more import is needed

**Pull request merged**
